CREATE TABLE CRON_ATTRIBUTES(
CRONID INT  PRIMARY KEY, 
SECONDS VARCHAR(255),	    			
MINUTES VARCHAR(255),	    			
HOURS VARCHAR(255),
DAY_OF_MONTH VARCHAR(255),	    			
MONTH VARCHAR(255),	    			
DAY_OF_THE_WEEK VARCHAR(255)    			
);
